.TH "AutoClean" "29.04.2021"
.SH NAME
.B AutoClean
- aplikacja do segregowania plikow
.SH SYNOPSIS
.B AutoClean
[ -f | -h | -v ]
.SH DESCRIPTION
Uruchamia okienkowa lub terminalowa aplikacje.
.PP
Uzytkownik moze skorzystac z nastepujacych funkcjonalnosci:
 -automatyczne katalogowanie,
 -wybor sposobu katalogowania na 3 sposoby,
 -dodanie daty modyfikacji do nazwy pliku,
 -automatyczne katalogowanie subkatalogow.
.PP
Tryb okienkowy jest prezentowany przez 
.BR zenity .
.SS Options
.TP
.B -f
Wlacz program w trybie konsolowym (domyslnie okienkowy). Jezeli uzywasz tej opcji uzyj jej przed innymi!
.TP
.B -h
Otwiera manual, ktory wlasnie czytasz
.TP
.B -v
Wyswietla informacje o wersji i autorze
.SH FILES
.TP
.B AutoClean.sh
Plik skryptu
.TP
.B funkcje.rc
Funkcje niezbedne do prawidlowego funkcjonowania skryptu
.SH "SEE ALSO"
zenity(1)
.SH BUGS
Brak :) Jesli znalazles buga, prosze o kontakt.
.SH AUTHOR
Wojciech Panfil 184657
.I s184657@student.pg.edu.pl
