.TH man 1 "28.04.2021" "1.0" "Manual-AutoClean"
.SH NAME
.B AutoClean
- wyswietla okno z aplikacja do porzadkowania plikow lub robi to w terminalu.
Nie dotyka jednak plikow skryptu
.SH SYNOPSIS
autoclean.sh [SHORT-OPTION]
.SH DESCRIPTION
.B Aplikacja pozwala na:

\[bu] automatyczne porzadkowanie plikow poprzez katalogowanie

\[bu] mozliwosc zmiany klucza katalogowania (rok, inicjal, rozszerzenie)

\[bu] dopisywanie daty modyfikacji do nazwy pliku

\[bu] automatyczne segregowanie plikow ze wszystkich podkatalogow
.SH OPTIONS
-h - wyswietla pomoc korzystania z aplikacji

-v - wyswietla informacje o autorze i wersji

-f - wyswietla okno aplikacji - tryb okienkowy
.SH AUTHOR
184657 Wojciech Panfil
.SH BUGS
Opinie i uwagi prosze wysylac na adres mail: s184657@student.pg.edu.pl
.SH SEE ALSO
Wiecej informacji pod adresem sekurak.pl
